"use client";
import { useEffect,useState } from "react";
import { Luggage,LogOut,Plus,Copy,Download,KeyRound,BarChart3,Settings,FileText,Megaphone,ShieldCheck,Trash2,RefreshCw } from "lucide-react";
import { Toaster,toast } from "sonner";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from "@/components/ui/table";
import { Choose,Confirm } from "@/components/product-ui";
import { DEFAULT_CONFIG,type Config } from "@/lib/product-data";
import { api,copy,download } from "@/lib/client";
import { marketingTitles,marketingPosts,priceTests,candidates,scoreLabels } from "@/lib/marketing";
type Code={code:string;tier:string;enabled:number;uses:number;created:number;last_used:number|null};
export default function Admin(){
 const [auth,setAuth]=useState(false),[loading,setLoading]=useState(true),[password,setPassword]=useState(""),[loginError,setLoginError]=useState(""),[busy,setBusy]=useState(false);
 const [cfg,setCfg]=useState<Config>(DEFAULT_CONFIG),[codes,setCodes]=useState<Code[]>([]),[metrics,setMetrics]=useState<Record<string,number>>({}),[dirty,setDirty]=useState(false),[tab,setTab]=useState("codes"),[search,setSearch]=useState(""),[newCode,setNewCode]=useState(""),[count,setCount]=useState(10),[tier,setTier]=useState("full"),[generated,setGenerated]=useState<string[]>([]),[copyFallback,setCopyFallback]=useState(""),[current,setCurrent]=useState(""),[newPassword,setNewPassword]=useState(""),[repeat,setRepeat]=useState("");
 const [confirm,setConfirm]=useState<{title:string;description:string;yes:()=>void}|null>(null);
 const load=async()=>{const j=await api("dashboard");setAuth(true);setCfg(j.config);setCodes(j.codes);setMetrics(j.metrics);setDirty(false);};
 useEffect(()=>{load().catch(()=>{}).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const prevent=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",prevent);return()=>window.removeEventListener("beforeunload",prevent)},[dirty]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const change=(k:keyof Config,v:string|boolean)=>{setCfg(c=>({...c,[k]:v}));setDirty(true)};
 const save=()=>run(async()=>{const j=await api("save-config",{config:cfg});setCfg(j.config);setDirty(false);toast.success("已保存。前台重新打开立即生效，已打开页面将在 15 秒内同步。");});
 const doCopy=async(value:string)=>{try{await copy(value);toast.success("已复制。")}catch{setCopyFallback(value);toast.info("请在下方文本框中手动复制。")}};
 const exportCodes=()=>download("出发有数-兑换码.csv","\uFEFF兑换码,权益,状态,激活次数,最后激活时间\n"+codes.map(c=>[c.code,c.tier==="full"?"完整版":"基础版",c.enabled?"启用":"禁用",c.uses,c.last_used?new Date(c.last_used).toISOString():"未使用"].join(",")).join("\n"),"text/csv;charset=utf-8");
 const createCodes=(custom:boolean)=>run(async()=>{const j=await api("create-codes",{tier,...(custom?{code:newCode}:{count})});setGenerated(j.codes);setNewCode("");const data=await api("dashboard");setCodes(data.codes);toast.success(`已生成 ${j.codes.length} 个兑换码。`)});
 const refreshCodes=async()=>{const data=await api("dashboard");setCodes(data.codes);setMetrics(data.metrics)};
 const logout=()=>run(async()=>{await api("logout");setAuth(false);setPassword("");setDirty(false)});
 return <main className="shell admin-shell"><Toaster richColors position="top-center"/><header className="topbar"><a className="brand" href="/" target="_blank" rel="noreferrer"><span className="brand-icon"><Luggage size={23}/></span>{cfg.name}<span className="admin-badge">管理后台</span></a>{auth&&<button className="button ghost small" onClick={()=>dirty?setConfirm({title:"放弃未保存的修改并退出？",description:"前台不会收到未保存的内容。",yes:()=>void logout()}):void logout()}><LogOut size={16}/>退出</button>}</header>
 {!auth?<section className="admin-login panel"><div className="redeem-emblem"><ShieldCheck size={31}/></div><h1>欢迎回来</h1><p>登录后管理兑换码和产品内容。</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setLoginError("");try{await api("login",{password});await load();setPassword("")}catch(e){setLoginError((e as Error).message)}finally{setBusy(false)}}}><label className="field"><span>管理员密码</span><input type="password" autoComplete="current-password" required maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>{loginError&&<p role="alert" className="form-error">{loginError}</p>}<button className="button wide" disabled={busy||loading}>{loading?"正在读取…":busy?"正在登录…":"登录管理后台"}</button></form><p className="fine">首次登录使用交付给你的初始密码。登录后可以在安全设置中修改。</p></section>:<>
 <div className="section-head"><div><div className="eyebrow">日常运营，在这里完成</div><h1>产品管理</h1></div><a className="button ghost small" href="/" target="_blank" rel="noreferrer">查看用户页面</a></div><div className="stats-grid">{[["访问会话",metrics.visits||0],["激活次数",metrics.activations||0],["生成计划事件",metrics.plans||0],["已使用的兑换码",codes.filter(x=>x.uses>0).length]].map(([t,n])=><div className="stat" key={t}><span>{t}</span><strong>{n}</strong></div>)}</div><p className="fine">统计为累计事件，不等同于人数或销量。访问按浏览器 30 分钟去重，计划事件按 1 分钟去重；清除 Cookie 可能重复计数。</p>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="admin-tabs"><TabsTrigger value="codes"><KeyRound/>兑换码</TabsTrigger><TabsTrigger value="content"><FileText/>产品内容</TabsTrigger><TabsTrigger value="switches"><Settings/>开关与公告</TabsTrigger><TabsTrigger value="marketing"><Megaphone/>销售素材</TabsTrigger><TabsTrigger value="security"><ShieldCheck/>安全设置</TabsTrigger></TabsList>
 <TabsContent value="codes"><div className="admin-grid"><section className="panel"><h2>生成兑换码</h2><p className="muted">生成后直接复制，发给购买用户。允许同一码在多台设备使用。</p><Choose label="对应产品与权益" value={tier} onChange={setTier} options={[["full",`${cfg.name} · 完整版（清单 + 预算）`],["basic",`${cfg.name} · 基础版（清单）`]]}/><div className="inline-form"><label className="field"><span>批量数量（1–200）</span><input type="number" min="1" max="200" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><button className="button" disabled={busy} onClick={()=>createCodes(false)}><Plus size={17}/>批量生成</button></div><div className="inline-form"><label className="field"><span>或自定义一个兑换码</span><input placeholder="例如 CF-EXAMPLE01" maxLength={40} value={newCode} onChange={e=>setNewCode(e.target.value.toUpperCase())}/></label><button className="button secondary" disabled={busy||!newCode.trim()} onClick={()=>createCodes(true)}>新增</button></div></section><section className="panel generated-box"><h2>本次生成</h2>{generated.length?<><textarea aria-label="本次生成的兑换码" readOnly rows={7} value={generated.join("\n")}/><div className="button-row"><button className="button" onClick={()=>void doCopy(generated.join("\n"))}><Copy size={16}/>复制这批码</button><button className="button ghost" onClick={()=>download("本次兑换码.txt",generated.join("\n"))}>下载</button></div></>:<div className="empty-state compact"><KeyRound size={30}/><p>点击左侧生成，兑换码就会出现在这里。</p></div>}</section></div>
 <section className="panel"><div className="section-head"><h2>兑换码列表 <span className="pill">{codes.length} 个</span></h2><div className="button-row"><button className="button ghost small" disabled={busy} onClick={()=>void run(refreshCodes)} aria-label="刷新兑换码"><RefreshCw size={16}/></button><button className="button ghost small" onClick={exportCodes}><Download size={16}/>导出全部</button></div></div><input className="search" aria-label="搜索兑换码" placeholder="搜索兑换码" value={search} onChange={e=>setSearch(e.target.value)}/><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>兑换码</TableHead><TableHead>权益</TableHead><TableHead>使用情况</TableHead><TableHead>状态</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{codes.filter(c=>c.code.includes(search.toUpperCase())).map(c=><TableRow key={c.code}><TableCell className="code-cell">{c.code}</TableCell><TableCell>{c.tier==="full"?"完整版":"基础版"}</TableCell><TableCell>{c.uses?`${c.uses} 次激活`:"未使用"}{c.last_used&&<small className="block subtle">{new Date(c.last_used).toLocaleDateString("zh-CN")}</small>}</TableCell><TableCell><span className={c.enabled?"status-tag":"status-tag off"}>{c.enabled?"启用":"禁用"}</span></TableCell><TableCell><div className="table-actions"><button aria-label={`复制${c.code}`} onClick={()=>void doCopy(c.code)}><Copy size={16}/></button><button disabled={busy} onClick={()=>void run(async()=>{await api("toggle-code",{code:c.code,enabled:!c.enabled});await refreshCodes();toast.success(c.enabled?"已禁用，下次校验时取消使用资格。":"已恢复启用。")})}>{c.enabled?"禁用":"启用"}</button><button className="delete" aria-label={`删除${c.code}`} disabled={busy} onClick={()=>setConfirm({title:`删除 ${c.code}？`,description:"这会永久删除该兑换码，并撤销通过该码获得的激活状态。",yes:()=>void run(async()=>{await api("delete-code",{code:c.code});await refreshCodes();toast.success("已删除。")})})}><Trash2 size={16}/></button></div></TableCell></TableRow>)}</TableBody></Table></div>{!codes.filter(c=>c.code.includes(search.toUpperCase())).length&&<div className="empty-state compact"><p>{codes.length?"没有找到匹配的兑换码。":"还没有兑换码，先生成一批即可开始。"}</p></div>}<p className="fine">最多保留 5000 个码。禁用会在用户下一次校验时生效（打开页面、回到页面或最多约 15 秒），用户本机计划不会被删除。</p></section></TabsContent>
 <TabsContent value="content"><section className="panel editor-panel"><h2>面向用户的内容</h2><p className="muted">修改后点击保存，网站即刻读取新内容。</p><div className="form-grid">{([["name","产品名称"],["subtitle","首页主标题"],["price","参考售价（元）"]] as [keyof Config,string][]).map(([k,label])=><label className="field" key={k}><span>{label}</span><input maxLength={k==="name"?30:100} value={String(cfg[k])} onChange={e=>change(k,e.target.value)}/></label>)}</div>{([["description","首页介绍"],["instructions","使用说明"],["faq","常见问题（每行：问题|答案）"],["purchase","购买说明"],["contact","联系方式"],["disclaimer","免责声明"]] as [keyof Config,string][]).map(([k,label])=><label className="field" key={k}><span>{label}</span><textarea rows={k==="faq"?6:3} maxLength={5000} value={String(cfg[k])} onChange={e=>change(k,e.target.value)}/></label>)}<div className="save-bar"><span>{dirty?"有未保存的修改":"内容已保存"}</span><button className="button" disabled={busy||!dirty} onClick={save}>保存并生效</button></div></section></TabsContent>
 <TabsContent value="switches"><section className="panel editor-panel"><h2>产品开关</h2>{([["serviceOpen","产品开放","关闭后用户看到维护提示，管理员仍可登录。"],["redeemOpen","允许兑换","关闭后暂停新兑换，已激活用户继续使用。"],["packingOn","显示行李清单","控制行李清单模块的显示。"],["budgetOn","显示落地预算","控制预算模块的显示。"],["exportOn","允许保存与导出","控制备份与文字导出入口。"],["announcementOn","显示公告","开启后用户页面顶部显示公告。"]] as [keyof Config,string,string][]).map(([k,t,d])=><div className="switch-row" key={k}><div><strong>{t}</strong><p>{d}</p></div><Switch checked={!!cfg[k]} onCheckedChange={v=>change(k,v)} aria-label={t}/></div>)}<label className="field"><span>公告内容</span><textarea rows={3} maxLength={5000} value={cfg.announcement} onChange={e=>change("announcement",e.target.value)}/></label><label className="field"><span>暂停服务时的提示</span><textarea rows={3} maxLength={5000} value={cfg.maintenance} onChange={e=>change("maintenance",e.target.value)}/></label><div className="save-bar"><span>{dirty?"有未保存的修改":"设置已保存"}</span><button className="button" disabled={busy||!dirty} onClick={save}>保存并生效</button></div></section></TabsContent>
 <TabsContent value="marketing"><section className="panel"><div className="eyebrow">从真实使用场景开始</div><h2>帮第一次留学或长期出国的人，把行前事项、行李和预算整理在一起。</h2><p>建议从 ¥19.9 完整版开始小规模验证。以下为待测试的定价与文案，不是销量预测；发布前按实际产品名称、权益和购买渠道修改。若改过产品名，可复制后替换。</p><div className="price-tests">{priceTests.map(p=><article key={p.price}><strong>¥{p.price}</strong><h3>{p.title}</h3><p>{p.text}</p></article>)}</div><h3>10 个标题</h3><ol className="marketing-titles">{marketingTitles.map(t=><li key={t}>{t}<button aria-label={`复制标题${t}`} onClick={()=>void doCopy(t)}><Copy size={15}/></button></li>)}</ol><h3>3 套正文</h3>{marketingPosts.map((p,i)=><article className="marketing-post" key={i}><h3>{p.title}</h3><p className="preserve">{p.body}</p><button className="button ghost small" onClick={()=>void doCopy(p.body)}>复制正文</button></article>)}<h3>销售交付四步</h3><p>展示真实使用效果 → 在允许销售该类商品的渠道说明权益与售后 → 确认收到订单后生成并发送兑换码及用户网址 → 用户自助兑换。请先确认当前店铺类目和外链规则，页面不代收款。</p></section><section className="panel"><h2>选型记录 · TOP 10</h2><p>各项 1–10 分，分高更适合；风险与难度按“风险低、开发容易”评分。综合为 15 项等权均分，是产品判断而非真实付费调查。“扩展性”表示无需逐人配置，不代表无限免费流量。</p><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>方向 / 产品</TableHead>{scoreLabels.map(s=><TableHead key={s}>{s}</TableHead>)}<TableHead>均分</TableHead></TableRow></TableHeader><TableBody>{[...candidates].sort((a,b)=>b.scores.reduce((s,n)=>s+n,0)-a.scores.reduce((s,n)=>s+n,0)).map(c=><TableRow key={c.name}><TableCell className="candidate-name">{c.name}</TableCell>{c.scores.map((n,i)=><TableCell key={i}>{n}</TableCell>)}<TableCell>{(c.scores.reduce((s,n)=>s+n,0)/15).toFixed(2)}</TableCell></TableRow>)}</TableBody></Table></div><p>选择出发准备工具：任务具体、清单与预算可以直接展示、静态内容维护少；同类免费模板很多，付费理由需要通过“手机直接用、按场景筛选、行李数量重量、预算联动和备份”来验证。</p><p>下一款可复制：搬家有数，复用兑换码和后台，把内容替换为搬家时间线、打包清单与搬家预算。</p></section></TabsContent>
 <TabsContent value="security"><section className="panel editor-panel"><h2>修改管理员密码</h2><p>修改后其他管理会话会失效。密码只在服务器校验，不包含在用户页面中。</p><form onSubmit={e=>{e.preventDefault();if(newPassword!==repeat)return toast.error("两次新密码不一致。");void run(async()=>{await api("password",{current,password:newPassword});setCurrent("");setNewPassword("");setRepeat("");toast.success("密码已修改，请妥善保存。")})}}><label className="field"><span>原密码</span><input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label className="field"><span>新密码（至少 12 个字符）</span><input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label className="field"><span>确认新密码</span><input required type="password" minLength={12} autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></label><button className="button" disabled={busy}>修改密码</button></form></section><section className="panel editor-panel"><h2>运营备份</h2><p>导出当前产品文案、开关和兑换码列表，便于留档。此文件不包含管理员密码，也不包含用户本机计划。</p><button className="button ghost" onClick={()=>download("出发有数-运营备份.json",JSON.stringify({exportedAt:new Date().toISOString(),config:cfg,codes,metrics},null,2),"application/json")}><Download size={16}/>导出运营备份</button></section></TabsContent>
 </Tabs>{copyFallback&&<section className="panel"><h3>手动复制</h3><textarea readOnly rows={6} value={copyFallback} onFocus={e=>e.target.select()}/><button className="text-button" onClick={()=>setCopyFallback("")}>收起</button></section>}<footer className="footer"><p>管理登录在 12 小时后过期。用户页面不提供后台入口；请收藏当前管理网址。</p></footer>
 </>}{confirm&&<Confirm title={confirm.title} description={confirm.description} onYes={confirm.yes} onClose={()=>setConfirm(null)}/>}</main>;
}
