"use client";
import { useEffect,useRef,useState } from "react";
import { Luggage,Check,CalendarDays,Wallet,ListChecks,Plus,Trash2,Download,Copy,Settings2,MapPin,ShieldCheck,LockKeyhole,RotateCcw,Upload,FileText,Plane,CheckCheck } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { Toaster,toast } from "sonner";
import { Choose,Modal,Confirm } from "@/components/product-ui";
import { DEFAULT_CONFIG,DESTINATIONS,STAGES,CATEGORIES,TEMPLATE_COUNT,defaultProfile,generatePlan,budgetTotals,validPlan,type Config,type Plan,type Profile,type Item } from "@/lib/product-data";
import { api,download,copy } from "@/lib/client";
const STORAGE="chufa-plan-v1";
const money=(n:number)=>n.toLocaleString("zh-CN",{maximumFractionDigits:2});
export default function Product(){
 const [cfg,setCfg]=useState<Config>(DEFAULT_CONFIG),[license,setLicense]=useState<{tier:string}|null>(null),[connected,setConnected]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState("");
 const [screen,setScreen]=useState("home"),[plan,setPlan]=useState<Plan|null>(null),[profile,setProfile]=useState(defaultProfile),[demo,setDemo]=useState(false),[tab,setTab]=useState("tasks"),[filter,setFilter]=useState("全部"),[search,setSearch]=useState("");
 const [modal,setModal]=useState(""),[code,setCode]=useState(""),[codeError,setCodeError]=useState(""),[busy,setBusy]=useState(false),[customTitle,setCustomTitle]=useState(""),[customNote,setCustomNote]=useState(""),[customGroup,setCustomGroup]=useState(STAGES[0]),[editing,setEditing]=useState<string|null>(null),[storageError,setStorageError]=useState("");
 const [confirm,setConfirm]=useState<{title:string;description:string;yes:()=>void}|null>(null),[copyText,setCopyText]=useState("");
 const fileRef=useRef<HTMLInputElement>(null),initial=useRef(true),stored=useRef<Plan|null>(null);
 const refresh=async()=>{try{const r=await fetch("/api/service",{cache:"no-store"});const j=await r.json() as {config:Config;license:{tier:string}|null;error:string};if(!r.ok)throw new Error(j.error);setCfg(j.config);setLicense(j.license);setConnected(true);setError("");if(initial.current){initial.current=false;if(j.license){setDemo(false);setScreen(stored.current?"work":"setup");}}}catch{setConnected(false);setError("暂时无法连接服务。已有计划仍保存在本机，请恢复连接后重试。");}finally{setLoaded(true)}};
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){const p=JSON.parse(raw);if(validPlan(p)){stored.current=p;setPlan(p);setProfile(p.profile);}else setStorageError("本机备份格式无法读取，原始数据尚未覆盖。可先导出原始数据，再重新开始。");}}catch{setStorageError("当前浏览器无法读取本机数据，请检查存储权限或切换普通浏览器。");}void refresh();void api("event",{event:"visits"}).catch(()=>{});const timer=setInterval(()=>{if(!document.hidden)void refresh()},15000);const focus=()=>void refresh();window.addEventListener("focus",focus);return()=>{clearInterval(timer);window.removeEventListener("focus",focus)};},[]);
 useEffect(()=>{if(!loaded||!plan||demo||storageError)return;try{localStorage.setItem(STORAGE,JSON.stringify(plan));stored.current=plan;}catch{setStorageError("本机存储空间不足或已被禁用。当前内容仍在页面，请立即导出备份。");}},[plan,demo,loaded,storageError]);
 useEffect(()=>{document.title=cfg.name+" · 行前清单与落地预算"},[cfg.name]); useEffect(()=>{if((tab==="packing"&&!cfg.packingOn)||(tab==="budget"&&!cfg.budgetOn))setTab("tasks")},[cfg.packingOn,cfg.budgetOn,tab]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:"read_departure_summary",title:"查看出发准备进度",description:"只读当前可见计划的完成进度和预算合计；不读取具体个人备注。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("不接受参数");if(screen!=="work"||!plan||!cfg.serviceOpen||(!demo&&!license))throw new Error("请先打开可用计划");return {destination:plan.profile.destination,completed:plan.items.filter(x=>x.done).length,total:plan.items.length,budget:cfg.budgetOn&&(demo||license?.tier==="full")?budgetTotals(plan).total:null,currency:plan.currency};}}, {signal:life.signal})).catch(()=>{});return()=>life.abort()},[plan,screen,demo,license,cfg.serviceOpen,cfg.budgetOn]);
 const patch=(v:Partial<Plan>)=>setPlan(p=>p?{...p,...v,updatedAt:new Date().toISOString()}:p);
 const updateItem=(id:string,v:Partial<Item>)=>plan&&patch({items:plan.items.map(x=>x.id===id?{...x,...v}:x)});
 const workAllowed=demo||!!license;const budgetAllowed=demo||license?.tier==="full";
 const openRedeem=()=>{setCodeError("");setCode("");setModal("redeem")};
 const start=()=>{if(!connected)return void toast.error("请先恢复连接并重试。");if(!cfg.serviceOpen)return;if(license){setDemo(false);setPlan(stored.current);setScreen(stored.current?"work":"setup")}else openRedeem()};
 const showDemo=()=>{const p=generatePlan({...defaultProfile(),date:new Date(Date.now()+42*86400000).toISOString().slice(0,10)});p.items=p.items.map((x,i)=>({...x,done:i<6}));p.budget=p.budget.map((x,i)=>({...x,amount:[4500,6000,1500,800,5000,2200,600,150,500][i]}));setPlan(p);setDemo(true);setScreen("work");setTab("tasks");setFilter("全部");window.scrollTo({top:0,behavior:"smooth"})};
 const redeem=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setCodeError("");try{const j=await api("redeem",{code});setLicense(j.license);setModal("");setDemo(false);setPlan(stored.current);setProfile(stored.current?.profile||defaultProfile());setScreen(stored.current?"work":"setup");toast.success("兑换成功，开始准备你的出发计划。")}catch(e){setCodeError((e as Error).message)}finally{setBusy(false)}};
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(!license)return openRedeem();if(!profile.date)return toast.error("请选择出发日期。");setBusy(true);try{await api("event",{event:"plans"});const next=generatePlan(profile);setDemo(false);setPlan(next);setScreen("work");setTab("tasks");setFilter("全部");toast.success("清单已生成，可以按实际需要增删。")}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const exportBackup=()=>{if(!plan)return;download("出发有数-计划备份.json",JSON.stringify(plan,null,2),"application/json");toast.success("已发起保存；如浏览器未下载，可以复制完整备份。");};
 const summary=()=>{if(!plan)return "";const totals=budgetTotals(plan);return `${cfg.name} · ${plan.profile.destination}\n出发日期：${plan.profile.date}\n\n`+plan.items.filter(x=>x.kind!=="pack"||cfg.packingOn).map(x=>`${x.done?"☑":"☐"} ${x.title}${x.kind==="pack"?` × ${x.quantity}`:""}${x.note?` — ${x.note}`:""}`).join("\n")+(budgetAllowed&&cfg.budgetOn?`\n\n${plan.profile.months} 个月预算：${plan.currency} ${money(totals.total)}\n计算方式：一次性 ${money(totals.once)} + 每月 ${money(totals.monthly)} × ${plan.profile.months}，另加 ${plan.reserve}% 预留。\n` : "")+`\n${cfg.disclaimer}`};
 const copyResult=async()=>{try{await copy(summary());toast.success("清单已复制。")}catch{setCopyText(summary());setModal("copy")}};
 const importFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(file.size>500000)return toast.error("备份文件过大，请选择本工具导出的文件。");try{const p=JSON.parse(await file.text());if(!validPlan(p))throw new Error("备份格式不正确，未更改当前计划。");setConfirm({title:"导入这份计划？",description:"导入会替换当前计划，建议先导出当前备份。",yes:()=>{setPlan(p);setProfile(p.profile);setScreen("work");setDemo(false);setStorageError("");toast.success("备份已导入。")}})}catch(e){toast.error((e as Error).message||"文件无法读取。")}};
 const addItem=()=>{if(!plan||!customTitle.trim())return;const kind=tab==="packing"?"pack":"task";const fields={title:customTitle.trim(),note:customNote.trim(),category:kind==="pack"?customGroup:"行前待办",stage:kind==="task"?customGroup:""};if(editing)updateItem(editing,fields);else{if(plan.items.length>=500)return toast.error("单个计划最多保留 500 项。");patch({items:[...plan.items,{...fields,id:crypto.randomUUID(),done:false,quantity:1,weight:0,kind,custom:true}]})}setModal("");setCustomTitle("");toast.success(editing?"已修改。":"已加入清单。")};
 const editItem=(item?:Item)=>{setEditing(item?.id||null);setCustomTitle(item?.title||"");setCustomNote(item?.note||"");setCustomGroup(item?(item.kind==="pack"?item.category:item.stage):(tab==="packing"?CATEGORIES[0]:STAGES[0]));setModal("add")};
 const done=plan?.items.filter(x=>x.done).length||0,total=plan?.items.length||0,percent=total?Math.round(done/total*100):0;
 const today=new Date(); const days=plan?.profile.date?Math.round((Date.parse(plan.profile.date+"T00:00:00Z")-Date.UTC(today.getFullYear(),today.getMonth(),today.getDate()))/86400000):0;
 const footer=<footer className="footer"><div className="footer-brand"><Luggage size={19}/>{cfg.name}<span>慢慢准备，好好出发。</span></div><div className="footer-links"><button onClick={()=>setModal("help")}>使用说明</button><button onClick={()=>setModal("privacy")}>隐私说明</button><button onClick={()=>setModal("terms")}>服务说明</button><button onClick={()=>setModal("contact")}>联系与购买</button></div><p>{cfg.disclaimer}</p></footer>;
 return <main className="shell"><Toaster richColors position="top-center"/><header className="topbar"><button className="brand brand-button" onClick={()=>setScreen("home")}><span className="brand-icon"><Luggage size={23}/></span>{cfg.name}<span className="brand-note">YOUR NEXT CHAPTER</span></button><div className="header-actions">{screen!=="home"&&<button className="plain" onClick={()=>setScreen("home")}>首页</button>}<button className="button small" onClick={start}>{license?"我的计划":"输入兑换码"}</button></div></header>
 {cfg.announcementOn&&<div className="notice">{cfg.announcement}</div>}{error&&<div role="alert" className="error-line">{error}<button onClick={()=>void refresh()}>重试</button></div>}
 {!cfg.serviceOpen?<section className="empty-state"><Luggage size={48}/><h1>稍作停留，再出发</h1><p>{cfg.maintenance}</p><button className="button" onClick={()=>void refresh()}>刷新查看</button></section>:screen==="home"?<>
 <section className="hero"><div className="hero-copy"><div className="eyebrow">留学 · 工作 · 远方的生活</div><h1>{cfg.subtitle===DEFAULT_CONFIG.subtitle?<>把远行，<br/>准备得<span>明明白白。</span></>:cfg.subtitle}</h1><p>{cfg.description}</p><div className="hero-actions"><button className="button" onClick={showDemo}>免费体验示例</button><button className="text-button" onClick={start}>{license?"继续我的计划":"立即使用"}</button></div><div className="hero-proof"><span><Check size={16}/>清单随手勾</span><span><Check size={16}/>预算心中有数</span><span><Check size={16}/>个人数据留在本机</span></div></div><div className="hero-photo"><img src="/travel.png" alt="整齐收纳衣物和旅行用品的蓝色行李箱"/><div className="photo-caption"><span>下一站，新生活</span><strong>READY WHEN YOU ARE.</strong></div></div></section>
 <section className="section-head"><div><div className="eyebrow">一份计划，装下出发前的大小事</div><h2>你的出发准备台</h2></div><span className="pill">3 个实用模块</span></section><div className="feature-grid">{[{Icon:CalendarDays,n:"01",t:"行前时间线",d:"从提前三个月，到落地第一周。"},...(cfg.packingOn?[{Icon:ListChecks,n:"02",t:"行李清单",d:"按生活场景整理，带上真正需要的。"}]:[]),...(cfg.budgetOn?[{Icon:Wallet,n:"03",t:"落地预算",d:"拆开一次性与每月支出，算得更清楚。"}]:[])].map(({Icon,n,t,d})=><article className="feature" key={n}><div className="feature-top"><Icon size={26}/><span>{n}</span></div><h3>{t}</h3><p>{d}</p></article>)}</div>
 <section className="demo-strip"><div><div className="eyebrow">先看看，它可以帮你做什么</div><h2>英国留学 · 12 个月</h2><p>示例包含待办、行李和可编辑预算。所有示例数字仅用于演示。</p><button className="button ghost" onClick={showDemo}>打开示例计划</button></div><div className="mini-checks">{["确认住宿起止日期","整理重要文件备份","规划机场到住处的路线"].map((t,i)=><div key={t}><span className={i===0?"mini-check checked":"mini-check"}>{i===0&&<Check size={15}/>}</span>{t}<span>{i===0?"已准备":"待准备"}</span></div>)}</div></section>
 <section className="price-band"><div><span className="eyebrow">准备，从清楚开始</span><h2>创建属于你的出发计划</h2><p>{TEMPLATE_COUNT} 条内置准备提示，按场景筛选，内容随你增删。</p></div><div className="price-side"><p><span>参考售价</span><strong>¥{cfg.price}</strong></p><button className="button" onClick={start}>输入兑换码，立即使用</button></div></section><section className="faq"><h2>开始前，你可能想知道</h2>{cfg.faq.split("\n").filter(Boolean).map((row,i)=>{const [q,...a]=row.split("|");return <details key={i}><summary>{q}</summary><p>{a.join("|")}</p></details>})}</section>
 </>:screen==="setup"&&license?<section className="setup-page"><div className="eyebrow">开始一份新计划</div><h1>这一次，准备去哪里？</h1><p className="muted">选好生活场景，我们帮你整理第一版清单。所有内容都可以再修改。</p><form className="panel setup-form" onSubmit={create}><div className="form-grid"><Choose label="目的地" value={profile.destination} options={DESTINATIONS} onChange={v=>setProfile({...profile,destination:v})}/><label className="field"><span>出发日期</span><input type="date" required value={profile.date} onInput={e=>{const date=e.currentTarget.value;setProfile(p=>({...p,date}))}} onChange={e=>setProfile(p=>({...p,date:e.target.value}))}/></label><Choose label="这次出发是为了" value={profile.purpose} options={[["study","留学 / 交换"],["work","工作 / 实习"],["life","长期生活"]]} onChange={v=>setProfile({...profile,purpose:v})}/><Choose label="预计抵达时的气候" value={profile.climate} options={[["mild","温和 / 多变"],["cold","偏冷"],["warm","偏热"]]} onChange={v=>setProfile({...profile,climate:v})}/><Choose label="住宿安排" value={profile.housing} options={[["dorm","学校宿舍"],["rental","自行租住"],["other","其他 / 尚未确定"]]} onChange={v=>setProfile({...profile,housing:v})}/><label className="field"><span>计划时长（月）</span><input type="number" min="1" max="60" step="1" required value={profile.months} onChange={e=>setProfile({...profile,months:Number(e.target.value)})}/></label></div><p className="fine">规则说明：气候决定衣物提示，住宿与出行目的决定相应待办；目的地用于计划标记，不自动提供当地法规或实时价格。</p><button className="button wide" disabled={busy||!connected}>{busy?"正在生成…":"生成我的准备清单"}</button></form>{stored.current&&<button className="text-button" onClick={()=>{setPlan(stored.current);setScreen("work")}}>返回已有计划</button>}</section>
 :screen==="work"&&plan&&workAllowed?<>
 {demo&&<div className="demo-banner"><span>免费示例 · 可以勾选和试算，内容不会覆盖你的计划。</span><button onClick={start}>{license?"回到我的计划":"解锁我的计划"}</button></div>}
 <div className="workspace-head"><div><div className="eyebrow">{demo?"示例计划":"我的出发计划"}</div><h1>{plan.profile.destination}<span className="purpose">{({study:"留学",work:"工作",life:"生活"} as any)[plan.profile.purpose]}</span></h1><p><MapPin size={15}/>{plan.profile.date} 出发 · {plan.profile.months} 个月<span className="save-label">{demo?"演示内容":storageError?"保存异常":"自动保存在本机"}</span></p></div><div className="countdown"><span>{days>0?"距离出发":days===0?"今天出发":"已经出发"}</span><strong>{Math.abs(days)}<small>天</small></strong></div></div>
 {storageError&&<div className="error-line">{storageError}<button onClick={()=>{try{download("出发有数-原始数据.txt",localStorage.getItem(STORAGE)||JSON.stringify(plan));}catch{exportBackup()}}}>保存现有数据</button><button onClick={()=>setStorageError("")}>重试保存</button></div>}
 <div className="workspace-layout"><div className="work-main"><div className="progress-card"><div><span>准备进度</span><strong>{percent}<small>%</small></strong></div><Progress value={percent} aria-label="准备进度"/><p>{done} / {total} 项已完成 · {percent===100?"准备得很认真，按自己的节奏出发。":"今天完成一点，也是在往前走。"}</p></div>
 <Tabs value={tab} onValueChange={v=>{setTab(v);setFilter("全部");setSearch("")}}><TabsList className="product-tabs"><TabsTrigger value="tasks"><CalendarDays/>行前待办</TabsTrigger>{cfg.packingOn&&<TabsTrigger value="packing"><Luggage/>行李清单</TabsTrigger>}{cfg.budgetOn&&<TabsTrigger value="budget"><Wallet/>落地预算</TabsTrigger>}<TabsTrigger value="result"><CheckCheck/>准备概览</TabsTrigger></TabsList>
 {(["tasks","packing"] as const).map(t=><TabsContent key={t} value={t}>{(t!=="packing"||cfg.packingOn)&&<><div className="list-toolbar"><input aria-label="搜索清单" placeholder="搜索清单里的物品或待办" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button secondary small" onClick={()=>editItem()}><Plus size={16}/>添加</button></div><div className="filter-row">{["全部","未完成","已完成"].map(x=><button aria-pressed={filter===x} className={filter===x?"active":""} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div>
 {t==="packing"&&<div className="weight-bar"><div><strong>{money(plan.items.filter(x=>x.kind==="pack").reduce((s,x)=>s+x.weight*x.quantity,0))} kg</strong><span>全部清单的预计总重量</span></div><label>自设总额度 <input aria-label="自设行李总额度" type="number" min="1" max="100" value={plan.allowance} onChange={e=>patch({allowance:Math.max(1,Math.min(100,Number(e.target.value)))})}/> kg</label><p>先填写物品的单件重量。不同箱包及托运、随身规则请自行核对，不把此总额当作航司额度。</p>{plan.items.filter(x=>x.kind==="pack").reduce((s,x)=>s+x.weight*x.quantity,0)>plan.allowance&&<p className="warning">预计重量超过你的自设总额，可以调整数量或重新分配。</p>}</div>}
 {(()=>{const rows=plan.items.filter(x=>x.kind===(t==="tasks"?"task":"pack")&&(filter==="全部"||(filter==="已完成"?x.done:!x.done))&&(x.title+x.note).toLowerCase().includes(search.toLowerCase()));const groups=Array.from(new Set([...(t==="tasks"?STAGES:CATEGORIES),...rows.map(x=>t==="tasks"?x.stage:x.category)]));return rows.length?groups.map((group,gi)=>{const list=rows.filter(x=>(t==="tasks"?x.stage:x.category)===group);return list.length?<section className="check-group" key={group}><h3><span className="group-index">{String(gi+1).padStart(2,"0")}</span>{group}<small>{list.length} 项</small></h3>{list.map(x=><div className={"check-item "+(x.done?"done":"")} key={x.id}><div className="check-top"><Checkbox className="item-checkbox" checked={x.done} onCheckedChange={v=>updateItem(x.id,{done:!!v})} aria-label={x.title}/><button className="item-copy" onClick={()=>editItem(x)}><strong>{x.title}</strong><span>{x.note}</span></button><button className="icon-button" aria-label={`删除${x.title}`} onClick={()=>setConfirm({title:"移除这项内容？",description:"不会影响其他清单项。可以稍后手动添加。",yes:()=>patch({items:plan.items.filter(i=>i.id!==x.id)})})}><Trash2 size={16}/></button></div>{t==="packing"&&<div className="item-details"><label>数量 <input aria-label={`${x.title}数量`} type="number" min="0" max="999" value={x.quantity} onChange={e=>updateItem(x.id,{quantity:Math.max(0,Math.min(999,Number(e.target.value)))})}/></label><label>单件 kg <input aria-label={`${x.title}单件重量`} type="number" min="0" max="100" step="0.01" value={x.weight} onChange={e=>updateItem(x.id,{weight:Math.max(0,Math.min(100,Number(e.target.value)))})}/></label><span>{money(x.weight*x.quantity)} kg</span></div>}</div>)}</section>:null}):<div className="empty-state compact"><ListChecks size={32}/><h3>{filter==="未完成"?"这一页都整理好了":"这里还没有清单项"}</h3><p>试试其他筛选，或添加自己的内容。</p><button className="button secondary" onClick={()=>{setFilter("全部");setSearch("")}}>查看全部</button></div>})()}</>}</TabsContent>)}
 <TabsContent value="budget">{!cfg.budgetOn?null:!budgetAllowed?<div className="empty-state compact"><LockKeyhole/><h3>落地预算需要完整版权益</h3><p>当前基础版可以使用行前待办与行李清单。</p><button className="button" onClick={openRedeem}>输入完整版兑换码</button></div>:<><div className="panel budget-intro"><h3>先填你了解的价格，再慢慢补齐。</h3><p>没有预设当地物价，所有金额由你填写；押金和预付款按现金准备计入，避免与月租重复统计。</p><div className="form-grid"><Choose label="记账币种（仅更改标记）" value={plan.currency} options={["CNY","GBP","USD","EUR","AUD","CAD","JPY","SGD","HKD"]} onChange={v=>patch({currency:v,rate:v==="CNY"?1:plan.rate})}/><label className="field"><span>1 {plan.currency} = 人民币（手填汇率）</span><input type="number" min="0.0001" max="10000" step="0.0001" disabled={plan.currency==="CNY"} value={plan.rate} onChange={e=>{const n=Number(e.target.value);if(n>0&&n<=10000)patch({rate:n})}}/></label><label className="field"><span>预算月数</span><input type="number" min="1" max="60" value={plan.profile.months} onChange={e=>patch({profile:{...plan.profile,months:Math.max(1,Math.min(60,Math.round(Number(e.target.value))))}})}/></label><label className="field"><span>自行预留（%）</span><input type="number" min="0" max="100" value={plan.reserve} onChange={e=>patch({reserve:Math.max(0,Math.min(100,Number(e.target.value)))})}/></label></div></div>{(["once","monthly"] as const).map(type=><section className="panel budget-section" key={type}><h3>{type==="once"?"一次性准备":"每月生活"}<span>{plan.currency}</span></h3>{plan.budget.filter(x=>x.type===type).map(x=><label className="budget-row" key={x.id}><span>{x.title}</span><input aria-label={x.title} type="number" min="0" max="100000000" step="0.01" value={x.amount} onChange={e=>patch({budget:plan.budget.map(b=>b.id===x.id?{...b,amount:Math.max(0,Math.min(1e8,Number(e.target.value)))}:b)})}/></label>)}</section>)}<BudgetResult plan={plan}/></>}</TabsContent>
 <TabsContent value="result"><div className="panel result-panel"><span className="eyebrow">你的准备，一眼看清</span><h2>{plan.profile.destination} · 出发准备概览</h2><div className="result-number">{done}<span> / {total} 项已完成</span></div><Progress value={percent}/><p>准备进度用于整理事项，不代表入境、报到或出行资格。</p><h3>接下来可以做</h3>{plan.items.filter(x=>!x.done).slice(0,3).map(x=><p className="next-item" key={x.id}><Check size={17}/>{x.title}</p>)}{done===total&&<p>清单已经完成，可以再次核对出行信息，保留自己的备份。</p>}{cfg.budgetOn&&budgetAllowed&&<BudgetResult plan={plan}/>}<div className="button-row">{cfg.exportOn&&<button className="button" onClick={copyResult}><Copy size={17}/>复制准备清单</button>}<button className="button ghost" onClick={()=>{setTab("tasks");setFilter("未完成")}}>继续整理</button></div></div></TabsContent>
 </Tabs></div><aside className="work-aside"><div className="aside-card"><div className="aside-icon"><Plane size={23}/></div><h3>少一点来回翻找，<br/>多一点从容出发。</h3><p>清单是起点，不是标准答案。点击项目文字即可编辑，留住对你有用的。</p><div className="rule-note"><ShieldCheck size={18}/><span>按出行目的、气候、住宿筛选。你始终可以自己调整。</span></div></div><div className="aside-card"><h3>保存与整理</h3>{cfg.exportOn?<><button className="aside-action" onClick={exportBackup}><Download size={18}/>下载完整备份</button><button className="aside-action" onClick={async()=>{try{await copy(JSON.stringify(plan));toast.success("完整备份已复制，请粘贴到自己的文本文件中保存。")}catch{setCopyText(JSON.stringify(plan));setModal("copy")}}}><Copy size={18}/>复制完整备份</button><button className="aside-action" onClick={()=>download("出发有数-准备清单.txt",summary())}><FileText size={18}/>保存文字清单</button><button className="aside-action" onClick={copyResult}><Copy size={18}/>复制准备清单</button>{!demo&&<button className="aside-action" onClick={()=>fileRef.current?.click()}><Upload size={18}/>导入备份</button>}{!demo&&<button className="aside-action" onClick={()=>{setCopyText("");setModal("restore")}}><FileText size={18}/>粘贴备份恢复</button>}</>:<p>导出功能暂未开放。</p>}<button className="aside-action" onClick={()=>setModal("help")}><Settings2 size={18}/>使用说明与规则</button>{!demo&&<button className="aside-action" onClick={()=>setConfirm({title:"重新生成计划？",description:"新的场景将生成新清单，替换当前的勾选与预算。建议先下载备份。",yes:()=>{setProfile(plan.profile);setScreen("setup")}})}><RotateCcw size={18}/>重新生成计划</button>}<p className="fine">个人计划只存在本浏览器，换设备前请先下载备份。</p></div>{!demo&&<button className="text-button" onClick={openRedeem}>重新输入兑换码</button>}</aside></div>
 </>:<div className="empty-state"><LockKeyhole/><h2>开始你的出发准备</h2><p>输入兑换码后，创建并保存自己的计划。</p><button className="button" onClick={openRedeem}>输入兑换码</button>{stored.current&&<button className="text-button" onClick={()=>{download("出发有数-已有计划备份.json",JSON.stringify(stored.current,null,2),"application/json")}}>备份本机已有计划</button>}</div>}
 {footer}<input type="file" accept=".json,application/json" hidden ref={fileRef} onChange={importFile}/>
 <Modal open={modal==="redeem"} onClose={()=>setModal("")} title="开启你的出发计划" description="输入购买后收到的兑换码，无需注册账号。"><div className="redeem-emblem"><Luggage size={30}/></div><form onSubmit={redeem}><label className="field"><span>兑换码</span><input autoComplete="off" autoCapitalize="characters" placeholder="输入兑换码" maxLength={40} required value={code} onChange={e=>setCode(e.target.value)}/></label>{codeError&&<p className="form-error" role="alert">{codeError}</p>}<button className="button wide" disabled={busy||!cfg.redeemOpen||!connected}>{busy?"正在验证…":!cfg.redeemOpen?"兑换暂时关闭":"验证并开始使用"}</button></form><p className="fine">{cfg.purchase}</p>{license&&<button className="text-button" onClick={async()=>{try{await api("reset-access");setLicense(null);setScreen("home");setModal("");toast.success("已退出激活状态，个人计划仍保留在本机。")}catch(e){toast.error((e as Error).message)}}}>退出当前激活状态</button>}</Modal>
 <Modal open={modal==="add"} onClose={()=>setModal("")} title={editing?"修改清单项":"加入一项自己的准备"} description="只记录准备事项，请勿填写证件号码等敏感信息。"><form onSubmit={e=>{e.preventDefault();addItem()}}><label className="field"><span>名称</span><input required maxLength={150} value={customTitle} onChange={e=>setCustomTitle(e.target.value)}/></label><Choose label="分类" value={customGroup} options={tab==="packing"?CATEGORIES:STAGES} onChange={setCustomGroup}/><label className="field"><span>备注</span><textarea maxLength={500} value={customNote} onChange={e=>setCustomNote(e.target.value)}/></label><button className="button wide">保存清单项</button></form></Modal>
 <Modal open={modal==="help"} onClose={()=>setModal("")} title="使用说明" description="让每一项准备都清楚可见。"><p className="preserve">{cfg.instructions}</p><h3>清单生成规则</h3><p>出行目的控制入学或入职事项；气候控制衣物提示；住宿类型控制入住事项。目的地不触发法律或签证判断。日期用于倒计时，时间线为一般准备顺序。</p><h3>预算如何计算</h3><p>总额 =（一次性支出 + 每月支出 × 月数）×（1 + 预留比例）。人民币估算 = 总额 × 你填写的汇率。切换币种不自动换算已有数字。</p></Modal>
 <Modal open={modal==="privacy"} onClose={()=>setModal("")} title="隐私说明" description="个人计划留在你自己的浏览器里。"><p>目的地、日期、清单、备注和预算仅存于本机浏览器，不上传我们的应用服务器。清除浏览器数据、使用无痕窗口或更换设备可能导致数据丢失。建议定期下载备份。</p><p>服务器保存兑换码、权益、激活次数及最近激活时间、管理设置和汇总访问计数。验证状态使用浏览器 Cookie 保存。服务器不收集你的姓名、手机号、证件号或支付信息。</p><p>托管平台可能处理基础请求日志。管理员登录失败限制使用网络地址的哈希值，不保存原始地址。备份文件由你自己保管。</p>{!demo&&plan&&<button className="button danger" onClick={()=>setConfirm({title:"清除本机计划？",description:"这会永久清除当前浏览器中的个人计划，不撤销兑换资格。请先导出备份。",yes:()=>{try{localStorage.removeItem(STORAGE);stored.current=null;setPlan(null);setScreen(license?"setup":"home");setModal("");setStorageError("")}catch{toast.error("未能清除，请检查浏览器存储权限。")}}})}>清除本机计划</button>}</Modal>
 <Modal open={modal==="terms"} onClose={()=>setModal("")} title="服务说明" description="一款帮助整理出行信息的自助工具。"><p>兑换码提供相应功能的使用资格，不包含人工咨询、代办或结果保证。基础版包括清单功能，完整版另含预算模块；服务存续期间可使用。</p><p>内置清单为通用提醒，可以自行增删。预算是用户填写的估算，不是实时物价或财务建议。数字商品权益、售后和退款请查看原购买渠道的约定。</p><p>托管服务有容量与可用性限制，可能短时维护或变更。请保留个人数据备份。如计划停止服务，将通过公告说明。</p><p>{cfg.disclaimer}</p></Modal>
 <Modal open={modal==="contact"} onClose={()=>setModal("")} title="联系与购买" description={`参考售价 ¥${cfg.price}，以购买渠道显示为准。`}><p className="preserve">{cfg.purchase}</p><p className="preserve">{cfg.contact}</p></Modal>
 <Modal open={modal==="copy"} onClose={()=>setModal("")} title="手动复制清单" description="当前浏览器没有允许自动复制，可以长按下面的文字全选复制。"><textarea readOnly rows={12} value={copyText} onFocus={e=>e.target.select()}/></Modal>
 <Modal open={modal==="restore"} onClose={()=>setModal("")} title="粘贴备份恢复" description="适合不方便下载或上传文件的浏览器。请粘贴本工具复制的完整备份文本。"><textarea aria-label="备份文本" rows={10} value={copyText} onChange={e=>setCopyText(e.target.value)} maxLength={500000}/><button className="button" onClick={()=>{try{const p=JSON.parse(copyText);if(!validPlan(p))throw new Error();setConfirm({title:"恢复这份备份？",description:"会替换当前计划，建议先复制或下载现有备份。",yes:()=>{setPlan(p);setProfile(p.profile);setScreen("work");setDemo(false);setStorageError("");setModal("");toast.success("备份已恢复。")}})}catch{toast.error("备份内容无法识别，未修改当前计划。")}}}>检查并恢复</button></Modal>
 {confirm&&<Confirm title={confirm.title} description={confirm.description} onYes={confirm.yes} onClose={()=>setConfirm(null)}/>}
 </main>
}
function BudgetResult({plan}:{plan:Plan}){const t=budgetTotals(plan);return <section className="budget-result"><div><span>{plan.profile.months} 个月预计需准备</span><strong>{plan.currency} {money(t.total)}</strong><p>约人民币 ¥{money(t.cny)} · 使用你填写的汇率</p></div><div className="budget-breakdown"><p><span>一次性</span><b>{money(t.once)}</b></p><p><span>每月 × {plan.profile.months}</span><b>{money(t.monthly)} × {plan.profile.months}</b></p><p><span>预留 {plan.reserve}%</span><b>{money(t.reserve)}</b></p></div>{t.total===0&&<p className="budget-empty">还没有填写支出。可以先从住宿、机票或餐饮开始。</p>}<p className="fine">请核对押金、预付房租是否重复计入。数字仅用于个人预算规划。</p></section>}




