import { env } from "cloudflare:workers";
import { DEFAULT_CONFIG, type Config } from "./product-data";
export const db=()=>{if(!env.DB)throw new Error("Storage unavailable");return env.DB;};
export async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,"0")).join("");}
export const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(24))).map(x=>x.toString(16).padStart(2,"0")).join("");
export async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(salt),iterations:100000,hash:"SHA-256"},key,256))).map(x=>x.toString(16).padStart(2,"0")).join("");}
function equal(a:string,b:string){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0;}
export async function config():Promise<Config>{const row=await db().prepare("SELECT value FROM settings WHERE key = 'config'").first<{value:string}>();return {...DEFAULT_CONFIG,...(row?JSON.parse(row.value):{})};}
export async function credential(password:string){const row=await db().prepare("SELECT value FROM settings WHERE key = 'admin'").first<{value:string}>();if(row){const {salt,digest}=JSON.parse(row.value);return equal(await passwordHash(password,salt),digest);}return !!env.ADMIN_PASSWORD&&equal(await hash(password),await hash(env.ADMIN_PASSWORD));}
export async function setPassword(password:string){const salt=random();await db().prepare("INSERT INTO settings (key,value) VALUES ('admin',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify({salt,digest:await passwordHash(password,salt)})).run();}
export function cookie(req:Request,name:string){return (req.headers.get("cookie")||"").split(";").map(s=>s.trim()).find(s=>s.startsWith(name+"="))?.slice(name.length+1)||"";}
export async function session(req:Request,kind:string){const raw=cookie(req,kind==="admin"?"chufa_admin":"chufa_access");if(!/^[a-f0-9]{48}$/.test(raw))return null;return db().prepare("SELECT code FROM sessions WHERE hash = ? AND kind = ? AND expires > ?").bind(await hash(raw),kind,Date.now()).first<{code:string|null}>();}
export async function license(req:Request){const s=await session(req,"user");if(!s?.code)return null;return db().prepare("SELECT tier FROM codes WHERE code = ? AND enabled = 1").bind(s.code).first<{tier:"full"|"basic"}>();}
export async function makeSession(req:Request,kind:string,code:string|null){const token=random(),seconds=kind==="admin"?43200:31536000;await db().prepare("INSERT INTO sessions (hash,kind,code,expires) VALUES (?,?,?,?)").bind(await hash(token),kind,code,Date.now()+seconds*1000).run();return `${kind==="admin"?"chufa_admin":"chufa_access"}=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${seconds}${new URL(req.url).protocol==="https:"?"; Secure":""}`;}
export async function metric(key:string){await db().prepare("INSERT INTO metrics (key,value) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET value=value+1").bind(key).run();}
export const reply=(body:unknown,status=200,setCookie?:string)=>Response.json(body,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff",...(setCookie?{"Set-Cookie":setCookie}:{})}});
